import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { withSupabase } from "npm:@supabase/server";

const corsHeaders={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,"Content-Type":"application/json"}});}
class HttpError extends Error{status:number;code:string;constructor(status:number,message:string,code="ERROR"){super(message);this.status=status;this.code=code;}}
function validUuid(v:unknown):v is string{return typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}
function serviceKey(){const modern=Deno.env.get("SUPABASE_SECRET_KEYS");if(modern){try{const p=JSON.parse(modern);if(p?.default)return String(p.default);}catch{}}return String(Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");}
function cfg(){const appId="1407687117661354";const appToken=String(Deno.env.get("META_APP_ACCESS_TOKEN")||"").trim();let appSecret=String(Deno.env.get("META_APP_SECRET")||"").trim();if(!appSecret&&appToken.startsWith(appId+"|"))appSecret=appToken.slice(appId.length+1);return{appId,appSecret,version:String(Deno.env.get("WHATSAPP_GRAPH_API_VERSION")||"v25.0")};}
async function graph(path:string,token:string,method="GET",body?:unknown){const c=cfg();const r=await fetch("https://graph.facebook.com/"+c.version+"/"+path,{method,headers:{Authorization:"Bearer "+token,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify(body):undefined});const text=await r.text();let p:any;try{p=JSON.parse(text)}catch{p={raw:text}};if(!r.ok)throw new HttpError(502,p?.error?.message||"Meta rechazó la operación","META_GRAPH_ERROR");return p;}
async function exchangeCode(code:string){const c=cfg();if(!c.appSecret)throw new HttpError(500,"Falta META_APP_SECRET para completar Embedded Signup","META_APP_SECRET_MISSING");const u=new URL("https://graph.facebook.com/"+c.version+"/oauth/access_token");u.searchParams.set("client_id",c.appId);u.searchParams.set("client_secret",c.appSecret);u.searchParams.set("code",code);const r=await fetch(u.toString());const p=await r.json().catch(()=>({}));if(!r.ok||!p?.access_token)throw new HttpError(502,p?.error?.message||"Meta no pudo intercambiar el código","META_CODE_EXCHANGE_FAILED");return String(p.access_token);}
const templates=[
{name:"htpweb_local_order_brand_v1",language:"es",category:"UTILITY",allow_category_change:true,components:[{type:"BODY",text:"Nuevo pedido de {{1}}\nPedido {{2}}\nLOCAL: {{3}}\nProductos: {{4}}\nObservaciones: {{5}}\nResponde con los minutos de preparación (por ejemplo, 20). Cuando esté listo, responde LISTO.\n\nPlataforma HTPWEB",example:{body_text:[["Sobre Ruedas","A1B2C3D4","Asados Codesa","2 x Parrillada; 1 x Cola","Sin observaciones"]]}}]},
{name:"htpweb_driver_assignment_brand_v1",language:"es",category:"UTILITY",allow_category_change:true,components:[{type:"BODY",text:"Nuevo pedido asignado por {{1}}\nPedido {{2}}\nAbre este enlace para ver recogida, ruta y entrega:\n{{3}}\n\nPlataforma HTPWEB",example:{body_text:[["Sobre Ruedas","A1B2C3D4","https://htpweb.github.io/htpweb/admin/index.html"]]}}]},
{name:"htpweb_driver_unassignment_brand_v1",language:"es",category:"UTILITY",allow_category_change:true,components:[{type:"BODY",text:"Actualización de {{1}}\nEl pedido {{2}} ya no está asignado a ti.\n\nPlataforma HTPWEB",example:{body_text:[["Sobre Ruedas","A1B2C3D4"]]}}]}
];
async function ensureTemplates(wabaId:string,token:string){const cur=await graph(wabaId+"/message_templates?limit=100",token);const existing=new Map((cur?.data||[]).map((t:any)=>[String(t.name),t]));const out:any[]=[];for(const tpl of templates){const old:any=existing.get(tpl.name);if(old){out.push({name:tpl.name,action:"exists",status:old.status||null});continue;}try{const made=await graph(wabaId+"/message_templates",token,"POST",tpl);out.push({name:tpl.name,action:"created",id:made?.id||null,status:"PENDING"});}catch(e){out.push({name:tpl.name,action:"error",error:e instanceof Error?e.message:"error"});}}return out;}
const handler=withSupabase({auth:"user"},async(req:Request,ctx:any)=>{try{if(req.method!=="POST")throw new HttpError(405,"Método no permitido","METHOD_NOT_ALLOWED");const b=await req.json().catch(()=>({}));const deliveryId=String(b?.delivery_id||"");const code=String(b?.code||"");const wabaId=String(b?.waba_id||"");const phoneId=String(b?.phone_number_id||"");const businessId=b?.business_id?String(b.business_id):null;if(!validUuid(deliveryId))throw new HttpError(400,"delivery_id inválido","INVALID_DELIVERY");if(!code||!/^\d+$/.test(wabaId)||!/^\d+$/.test(phoneId))throw new HttpError(400,"Datos de Embedded Signup incompletos","INVALID_META_SIGNUP");
const{data:allowed,error:allowedError}=await ctx.supabase.rpc("delivery_whatsapp_connection_snapshot",{p_delivery_id:deliveryId});if(allowedError||!allowed)throw new HttpError(403,allowedError?.message||"No autorizado para este DELIVERY","FORBIDDEN");
const token=await exchangeCode(code);const phones=await graph(wabaId+"/phone_numbers?fields=id,display_phone_number,verified_name,code_verification_status",token);const phone=(phones?.data||[]).find((p:any)=>String(p.id)===phoneId);if(!phone)throw new HttpError(422,"El número seleccionado no pertenece al WABA autorizado","PHONE_NOT_IN_WABA");await graph(wabaId+"/subscribed_apps",token,"POST",{});const templateResults=await ensureTemplates(wabaId,token);
const adminUrl=String(Deno.env.get("SUPABASE_URL")||"");const key=serviceKey();if(!adminUrl||!key)throw new HttpError(500,"Supabase admin no está configurado","SUPABASE_ADMIN_NOT_CONFIGURED");const admin=createClient(adminUrl,key,{auth:{persistSession:false,autoRefreshToken:false}});
const{error:updateError}=await admin.schema("private").from("delivery_whatsapp_connections").update({connection_mode:"HTPWEB_MANAGED",status:"CONNECTED",environment:"PRODUCTION",credential_source:"PLATFORM",meta_business_id:businessId,waba_id:wabaId,phone_number_id:phoneId,display_phone:phone.display_phone_number||null,verified_name:phone.verified_name||null,token_secret_name:null,last_error:null,connected_at:new Date().toISOString(),approved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("delivery_id",deliveryId);if(updateError)throw new HttpError(500,updateError.message,"CONNECTION_SAVE_FAILED");
return json({ok:true,delivery_id:deliveryId,waba_id:wabaId,phone_number_id:phoneId,display_phone:phone.display_phone_number||null,verified_name:phone.verified_name||null,templates:templateResults});
}catch(error){console.error("meta-whatsapp-connect:",error);return json({ok:false,code:error instanceof HttpError?error.code:"UNKNOWN_ERROR",error:error instanceof Error?error.message:"Error desconocido"},error instanceof HttpError?error.status:500);}});
Deno.serve((req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});return handler(req);});
