\set ON_ERROR_STOP on
select set_config('test.role','MASTER',false);
select set_config('test.uid','00000000-0000-4000-8000-000000000001',false);
do $$
declare c uuid; c2 uuid; d uuid; d2 uuid; z1 uuid; z2 uuid; l1 uuid; l2 uuid; l3 uuid; g1 uuid; bc uuid; failed boolean;
begin
  assert public.htp_zone_contains('[[0,0],[0,2],[2,2],[2,0]]',1,1);
  assert not public.htp_zone_contains('[[0,0],[0,2],[2,2],[2,0]]',3,1);
  assert public.htp_zone_contains('[[0,0],[0,2],[2,2],[2,0]]',0,1);
  failed:=false;
  begin perform public.htp_zone_polygon('[[0,0],[2,2],[0,2],[2,0]]'); exception when others then failed:=true; end;
  assert failed,'Self-intersections must fail';
  failed:=false;
  begin perform public.htp_zone_polygon('[[0,0],[1,1],[2,2]]'); exception when others then failed:=true; end;
  assert failed,'Zero area must fail';
  assert public.htp_zones_overlap('[[0,0],[0,2],[2,2],[2,0]]','[[1,1],[1,3],[3,3],[3,1]]');
  assert public.htp_zones_overlap('[[0,0],[0,2],[2,2],[2,0]]','[[0,1],[0,3],[2,3],[2,1]]');
  assert not public.htp_zones_overlap('[[0,0],[0,2],[2,2],[2,0]]','[[0,2],[0,4],[2,4],[2,2]]');
  assert not public.htp_zones_overlap('[[0,0],[0,2],[2,2],[2,0]]','[[3,3],[3,4],[4,4],[4,3]]');
  insert into public.cities(name,province) values('Cantón Prueba','Provincia Prueba') returning id into c;
  insert into public.cities(name,province) values('Otro Cantón','Provincia Prueba') returning id into c2;
  perform public.master_save_zone_v2(null,c2,'X20','Zona Otro Cantón','','#2563eb','[[6,6],[6,7],[7,7],[7,6]]',true);
  insert into public.deliveries(name,city_id) values('DELIVERY prueba',c) returning id into d;
  insert into public.deliveries(name,city_id) values('DELIVERY otro cantón',c2) returning id into d2;
  z1:=public.master_save_zone_v2(null,c,'X1','Centro','','#2563eb','[[0,0],[0,2],[2,2],[2,0]]',true);
  z2:=public.master_save_zone_v2(null,c,'X10','Fuera','','#2563eb','[[3,3],[3,5],[5,5],[5,3]]',true);
  perform public.set_delivery_zone(d,z1,true);
  l1:=public.master_save_local_v2(null,z1,'Local X1','','','',1,1,'','','place-test','','MAP',true);
  l2:=public.master_save_local_v2(null,z2,'Local X10','','','',4,4,'','',null,'','MAP',true);
  bc:=public.master_save_local_business_category(null,'Farmacias','Locales farmacéuticos',true);
  l3:=public.master_save_local_v3(null,c2,z1,bc,'Local cruzado','','','Calle prueba',1.5,1.5,'099','','place-cross','','MAP',true);
  assert exists(select 1 from public.locals where id=l3 and city_id=c2 and zone_id=z1 and business_category_id=bc),'LOCAL may use a zone whose reference canton differs';
  perform public.set_delivery_zone(d2,z1,true);
  assert public.htp_delivery_covers_local(d2,l3),'DELIVERY coverage follows selected zone, not delivery canton';
  update public.locals set active=false where id=l3;
  g1:=public.save_local_gallery_image(l1,null,'https://example.invalid/local-x1.webp','local/test/gallery/one',0);
  assert jsonb_array_length(public.list_local_gallery(l1))=1,'Gallery image should be listed';
  assert public.delete_local_gallery_image(l1,g1)='local/test/gallery/one','Gallery delete must return storage path';
  assert jsonb_array_length(public.list_local_gallery(l1))=0,'Gallery image should be removed';
  assert public.htp_delivery_covers_local(d,l1),'X1 should be visible';
  assert not public.htp_delivery_covers_local(d,l2),'X10 must not be visible';
  assert exists(select 1 from public.local_deliveries where local_id=l1 and delivery_id=d and active);
  assert not exists(select 1 from public.local_deliveries where local_id=l2 and delivery_id=d and active);
  failed:=false;
  begin insert into public.local_deliveries values(l2,d,true,now()); exception when others then failed:=true; end;
  assert failed,'Cannot bypass zone scope by manual assignment';
  failed:=false;
  begin perform public.master_save_local_v2(null,z1,'Wrong point','','','',8,8,'','',null,'','MAP',true); exception when others then failed:=true; end;
  assert failed,'Wrong zone should reject saving';
  failed:=false;
  begin perform public.master_save_local_v2(null,z1,'Duplicate','','','',1,1,'','','place-test','','MAP',true); exception when others then failed:=true; end;
  assert failed,'Google duplicate must be rejected';
  failed:=false;
  begin perform public.master_save_zone_v2(z1,c,'X1','Center','','#2563eb','[[0,0],[0,0.5],[0.5,0.5],[0.5,0]]',true); exception when others then failed:=true; end;
  assert failed,'Zone edit must not silently exclude a local';
  insert into public.order_locals(local_id) values(l1);
  perform public.set_delivery_zone(d,z1,false);
  assert not exists(select 1 from public.local_deliveries where local_id=l1 and delivery_id=d and active);
  assert exists(select 1 from public.order_locals where local_id=l1),'Historical orders must survive';
  perform public.set_delivery_zone(d,z1,true);
  failed:=false;
  begin perform public.master_save_local_business_category(null,'farmacias','Duplicada',true); exception when others then failed:=true; end;
  assert failed,'Duplicate LOCAL category names must fail case-insensitively';
  insert into public.user_deliveries values('00000000-0000-4000-8000-000000000002',d,true);
  perform set_config('test.role','DELIVERY_ADMIN',false);
  perform set_config('test.uid','00000000-0000-4000-8000-000000000002',false);
  failed:=false;
  begin perform public.set_delivery_zone(d,z2,true); exception when others then failed:=true; end;
  assert failed,'DELIVERY cannot self approve';
  perform public.request_delivery_zone(d,z2);
  assert exists(select 1 from public.delivery_zone_requests where delivery_id=d and zone_id=z2 and status='PENDING');
  assert not public.htp_delivery_covers_local(d,l2),'Pending is not coverage';
  failed:=false;
  begin perform public.master_save_zone_v2(null,c,'X3','Forbidden','','#2563eb',null,true); exception when others then failed:=true; end;
  assert failed,'Master RPC must reject DELIVERY';
end $$;
set role authenticated;
do $$ begin
  assert (select count(*) from public.locals)=1,'RLS must hide local X10 from DELIVERY';
  assert (select name from public.locals limit 1)='Local X1';
end $$;
reset role;
select 'Zone geometry, CRUD, coverage, history and RLS assertions passed';
