const $=id=>document.getElementById(id); const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const state={role:null,plans:[],deliveries:[],locals:[]};
function msg(t,e=false){$("message").textContent=t;$("message").className="message "+(e?"error":"success");}
async function rpc(n,a={}){const {data,error}=await supabaseClient.rpc(n,a);if(error)throw error;return data}
function lines(){return $("entitlements").value.split(/\n+/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const [type,code,raw]=line.split("|").map(x=>x?.trim());if(!["CAPABILITY","LIMIT"].includes(type)||!code)throw new Error("Prestación inválida en línea "+(i+1));const value=type==="CAPABILITY"?raw==="true":Number(raw);if(type==="LIMIT"&&(!Number.isFinite(value)||value<0))throw new Error("Límite inválido en línea "+(i+1));return{type,code,value}})}
function opts(type){const list=type==="DELIVERY"?state.deliveries:state.locals;return list.map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join("")}
function syncTargets(){["assignment","usage"].forEach(k=>$(k+"Target").innerHTML=opts($(k+"Type").value))}
function render(){ $("plans").innerHTML=state.plans.length?`<div class="plan-grid">${state.plans.map(p=>`<article class="plan-card"><h3>${esc(p.name)}</h3><strong>$${Number(p.price).toFixed(2)} ${esc(p.currency)}/${esc(p.billing_interval)}</strong><p>${esc(p.description||"")}</p><small>${esc(p.target_type)} · ${p.active?"Activo":"Inactivo"}</small>${state.role==="MASTER"?`<button data-edit="${p.id}" class="btn-muted">Editar</button>`:""}</article>`).join("")}</div>`:"<p class=muted>No hay planes.</p>"; $("assignmentPlan").innerHTML=state.plans.filter(p=>p.active).map(p=>`<option value="${p.id}" data-type="${p.target_type}">${esc(p.name)}</option>`).join(""); document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>edit(b.dataset.edit));}
async function load(){const user=await obtenerUsuarioActual();if(!user){location.href="../app/acceso.html";return}state.role=await rpc("current_role_code");document.querySelectorAll(".master-only").forEach(x=>x.classList.toggle("hidden",state.role!=="MASTER"));const [p,d,l]=await Promise.all([supabaseClient.from("subscription_plans").select("*").order("display_order"),supabaseClient.from("deliveries").select("id,name").order("name"),supabaseClient.from("locals").select("id,name").order("name")]);for(const r of[p,d,l])if(r.error)throw r.error;state.plans=p.data||[];state.deliveries=d.data||[];state.locals=l.data||[];render();syncTargets()}
async function edit(id){const p=state.plans.find(x=>x.id===id);const {data,error}=await supabaseClient.from("plan_entitlements").select("*").eq("plan_id",id).order("entitlement_type");if(error)throw error;$("planId").value=p.id;$("code").value=p.code;$("name").value=p.name;$("description").value=p.description||"";$("targetType").value=p.target_type;$("price").value=p.price;$("interval").value=p.billing_interval;$("order").value=p.display_order;$("active").checked=p.active;$("entitlements").value=(data||[]).map(e=>`${e.entitlement_type}|${e.code}|${JSON.stringify(e.value)}`).join("\n");scrollTo({top:0,behavior:"smooth"})}
function clearPlan(){["planId","code","name","description","entitlements"].forEach(x=>$(x).value="");$("price").value=0;$("order").value=0;$("active").checked=true}
$("savePlan").onclick=async()=>{try{await rpc("master_save_subscription_plan",{p_plan_id:$("planId").value||null,p_code:$("code").value,p_name:$("name").value,p_description:$("description").value,p_target_type:$("targetType").value,p_price:Number($("price").value),p_currency:"USD",p_billing_interval:$("interval").value,p_active:$("active").checked,p_display_order:Number($("order").value),p_entitlements:lines()});msg("Plan guardado.");clearPlan();await load()}catch(e){msg(e.message,true)}};
$("newPlan").onclick=clearPlan;["assignmentType","usageType"].forEach(id=>$(id).onchange=syncTargets);
$("assignmentPlan").onchange=()=>{const o=$("assignmentPlan").selectedOptions[0];if(o){$("assignmentType").value=o.dataset.type;syncTargets()}};
$("assignPlan").onclick=async()=>{try{const type=$("assignmentType").value,id=$("assignmentTarget").value;await rpc("master_assign_subscription_plan",{p_plan_id:$("assignmentPlan").value,p_delivery_id:type==="DELIVERY"?id:null,p_local_id:type==="LOCAL"?id:null,p_status:$("assignmentStatus").value,p_starts_at:new Date().toISOString(),p_ends_at:$("endsAt").value?new Date($("endsAt").value).toISOString():null,p_trial_ends_at:$("trialEndsAt").value?new Date($("trialEndsAt").value).toISOString():null,p_metadata:{source:"admin"}});msg("Plan asignado.")}catch(e){msg(e.message,true)}};
$("loadUsage").onclick=async()=>{try{const type=$("usageType").value,id=$("usageTarget").value;$("usage").textContent=JSON.stringify(await rpc("plan_usage_snapshot",{p_delivery_id:type==="DELIVERY"?id:null,p_local_id:type==="LOCAL"?id:null}),null,2)}catch(e){msg(e.message,true)}};
$("saveOverride").onclick=async()=>{try{const type=$("usageType").value,id=$("usageTarget").value,kind=$("overrideType").value,raw=$("overrideValue").value;const value=kind==="CAPABILITY"?raw==="true":Number(raw);await rpc("master_set_plan_override",{p_delivery_id:type==="DELIVERY"?id:null,p_local_id:type==="LOCAL"?id:null,p_entitlement_type:kind,p_code:$("overrideCode").value,p_value:value,p_reason:$("overrideReason").value});msg("Excepción guardada.");$("loadUsage").click()}catch(e){msg(e.message,true)}};
load().catch(e=>msg(e.message,true));